version: 2
jobs:
  code_analyze:
    docker:
      - image: circleci/openjdk:8
    steps:
      - run:
          name: Clone repository
          command: git clone https://bitbucket.org/devops_sysops/java.git
      - run:
          name: Run Maven SonarQube
          command: mvn sonar:sonar -Dsonar.projectKey=Java -Dsonar.sources=. -Dsonar.organization=$ORG -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN
workflows:
  version: 2
  test:
    jobs:
      - code_analyze